version: '3.7'

services:
  go_boilerplate:
    container_name: go_boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - go_boilerplate_volume:/opt/go_boilerplate:cached
    restart: unless-stopped
    env_file: .env
    ports:
      - "${SERVER_PORT}:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  # Redis
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - backend

volumes:
  mongo_data:
  go_boilerplate_volume:

networks:
  backend: