version: '3.7'

services:
  go_app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - go_app_volume:/opt/go_app:cached
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/ping"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    env_file: .env
    ports:
      - "${SERVER_PORT}:4000"
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  # MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    # restart: on-failure
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - backend

volumes:
  mongo_data:
  go_app_volume:

networks:
  backend:
